dependencies:
- base >= 4.7 && < 5
- transformers >= 0.5.6.2
- scientific >= 0.3.7.0
- containers >= 0.6.4.1
- bytestring >= 0.10.12.1
- zlib >= 0.6.3.0
- serialise >= 0.2.6.0
- directory >= 1.3.6.2
- time >= 1.9.3
- random >= 1.2.1.1
- haskeline >= 0.8.2
- text >= 1.2.5.0
- megaparsec >= 9.2.2
- parser-combinators >= 1.3.0
- prettyprinter >= 1.7.1
- prettyprinter-ansi-terminal >= 1.1.3

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hi

tests:
  hi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hi
